//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace design.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Shop_Basket
    {
        public int Id { get; set; }
        public Nullable<int> BuyerId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    
        public virtual T_Shop_Buyer T_Shop_Buyer { get; set; }
        public virtual T_Shop_Product T_Shop_Product { get; set; }
    }
}
